input_str_original = input()
w = eval(input())
input_str = input_str_original.strip()
print(input_str)
result = input_str[0].upper() + input_str[1:].lower()
print(result)
print(input_str.upper())
print(input_str.title())
result1 = input_str[:-1].lower() + input_str[-1].upper()
print(result1)
print(input_str.ljust(w))
print(input_str.rjust(w))
print(input_str.center(w))
print(input_str_original.lstrip())
print(input_str_original.rstrip())