N = int(input())
C1 = input()
F = float(input())
S1 = input()
C2 = input()
S2 = input()
print("%.2f"%(N+F))
ascii_value = ord(C1)
C_N = ascii_value + N
new_char = chr(C_N)
print(new_char,C_N)
ascii_value_1 = ord(C2)
C2_F = int(ascii_value_1+F)
new_char_1 = chr(C2_F)
print(new_char_1,C2_F)
lower_S1 = S1.lower()
print(lower_S1)
upper_S2 = S2.upper()
print(upper_S2)
